(function () {
    'use strict';

    angular.module('app', [
        'as.sortable',
        'env',
        'ngAnimate',
        'ngCropper',
        'ngFileUpload',
        'ngRoute',
        'ngSanitize',
        'toastr',
        'ui.bootstrap',
        'ui.select',
        'ui.mask',
        'datatables',
        'datatables.bootstrap',
        'mrImage',
        'ngLodash',
        'ngInflection',
        'ngTagsInput',
        'ui.sortable',
        'pascalprecht.translate',
        'angular-loading-bar',
        'vAccordion',
        'checklist-model',
        'ui.utils.masks',
        'ngScrollbars',
        'ngCookies',
        'thatisuday.dropzone',

        // App Modules
        'calendarModule',
        'clippingsModule',
        'componentsModule',
        'courseModule',
        'eventsModule',
        'featuredModule',
        'filterModule',
        'galleryModule',
        'helperModule',
        'indexModule',
        'mediaModule',
        'menuModule',
        'newMenuModule',
        'newsModule',
        'pagesModule',
        'periodicalModule',
        'releasesModule',
        'serviceModule',
        'loginModule',
        'faqModule',
        'tagsManagerModule',
        'useTermModule',
        'usersModule',
        'accountModule'
    ]);
})();
